/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/maimaixiong/dbcc */
#ifndef VW_H
#define VW_H

#include <stdint.h>
#include <stdio.h>

#include "ch.h"
#include "hal.h"

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

typedef PREPACK struct {
	uint16_t EPS_Berechneter_LW; /* scaling 0.1, offset 0.0, units Unit_DegreOfArc  */
	uint16_t EPS_Lenkmoment; /* scaling 1.0, offset 0.0, units Unit_centiNewtoMeter  */
	uint8_t CHECKSUM; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_HCA_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_Lenkungstyp; /* scaling 1.0, offset 0.0, units none  */
	uint8_t COUNTER; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_DSR_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_VZ_BLW; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_Lenkmoment_QBit; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_VZ_Lenkmoment; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_BLW_QBit; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x09f_LH_EPS_03_t;

typedef PREPACK struct {
	uint16_t ESP_HL_Radgeschw_02; /* scaling 0.0, offset 0.0, units Unit_KiloMeterPerHour  */
	uint16_t ESP_HR_Radgeschw_02; /* scaling 0.0, offset 0.0, units Unit_KiloMeterPerHour  */
	uint16_t ESP_VL_Radgeschw_02; /* scaling 0.0, offset 0.0, units Unit_KiloMeterPerHour  */
	uint16_t ESP_VR_Radgeschw_02; /* scaling 0.0, offset 0.0, units Unit_KiloMeterPerHour  */
} POSTPACK can_0x0b2_ESP_19_t;

typedef PREPACK struct {
	uint16_t TSK_Radbremsmom; /* scaling 8.0, offset 0.0, units Unit_NewtoMeter  */
	uint16_t TSK_ax_Getriebe_02; /* scaling 0.0, offset -2.0, units Unit_MeterPerSeconSquar  */
	uint8_t CHECKSUM; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TSK_zul_Regelabw; /* scaling 0.0, offset 0.0, units Unit_MeterPerSeconSquar  */
	uint8_t COUNTER; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TSK_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TSK_v_Begrenzung_aktiv; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TSK_Standby_Anf_ESP; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TSK_Freig_Verzoeg_Anf; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TSK_Limiter_ausgewaehlt; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TSK_Zwangszusch_ESP; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x120_TSK_06_t;

typedef PREPACK struct {
	uint16_t Assist_Torque; /* scaling 1.0, offset 0.0, units Nm  */
	uint8_t CHECKSUM; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SET_ME_0XFE; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SET_ME_0X07; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SET_ME_0X3; /* scaling 1.0, offset 0.0, units none  */
	uint8_t COUNTER; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Assist_Requested; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Assist_VZ; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HCA_Available; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HCA_Standby; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HCA_Active; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x126_HCA_01_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x09f_LH_EPS_03_time_stamp_rx;
	dbcc_time_stamp_t can_0x0b2_ESP_19_time_stamp_rx;
	dbcc_time_stamp_t can_0x120_TSK_06_time_stamp_rx;
	dbcc_time_stamp_t can_0x126_HCA_01_time_stamp_rx;
	unsigned can_0x09f_LH_EPS_03_status : 2;
	unsigned can_0x09f_LH_EPS_03_tx : 1;
	unsigned can_0x09f_LH_EPS_03_rx : 1;
	unsigned can_0x0b2_ESP_19_status : 2;
	unsigned can_0x0b2_ESP_19_tx : 1;
	unsigned can_0x0b2_ESP_19_rx : 1;
	unsigned can_0x120_TSK_06_status : 2;
	unsigned can_0x120_TSK_06_tx : 1;
	unsigned can_0x120_TSK_06_rx : 1;
	unsigned can_0x126_HCA_01_status : 2;
	unsigned can_0x126_HCA_01_tx : 1;
	unsigned can_0x126_HCA_01_rx : 1;
	can_0x09f_LH_EPS_03_t can_0x09f_LH_EPS_03;
	can_0x0b2_ESP_19_t can_0x0b2_ESP_19;
	can_0x120_TSK_06_t can_0x120_TSK_06;
	can_0x126_HCA_01_t can_0x126_HCA_01;
} POSTPACK can_obj_vw_h_t;

int unpack_message(can_obj_vw_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_vw_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_vw_h_t *o, const unsigned long id, BaseSequentialStream *output);

int decode_can_0x09f_EPS_Berechneter_LW(const can_obj_vw_h_t *o, double *out);
int encode_can_0x09f_EPS_Berechneter_LW(can_obj_vw_h_t *o, double in);
int decode_can_0x09f_EPS_Lenkmoment(const can_obj_vw_h_t *o, uint16_t *out);
int encode_can_0x09f_EPS_Lenkmoment(can_obj_vw_h_t *o, uint16_t in);
int decode_can_0x09f_CHECKSUM(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_CHECKSUM(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_EPS_HCA_Status(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_EPS_HCA_Status(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_EPS_Lenkungstyp(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_EPS_Lenkungstyp(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_COUNTER(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_COUNTER(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_EPS_DSR_Status(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_EPS_DSR_Status(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_EPS_VZ_BLW(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_EPS_VZ_BLW(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_EPS_Lenkmoment_QBit(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_EPS_Lenkmoment_QBit(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_EPS_VZ_Lenkmoment(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_EPS_VZ_Lenkmoment(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x09f_EPS_BLW_QBit(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x09f_EPS_BLW_QBit(can_obj_vw_h_t *o, uint8_t in);


int decode_can_0x0b2_ESP_HL_Radgeschw_02(const can_obj_vw_h_t *o, double *out);
int encode_can_0x0b2_ESP_HL_Radgeschw_02(can_obj_vw_h_t *o, double in);
int decode_can_0x0b2_ESP_HR_Radgeschw_02(const can_obj_vw_h_t *o, double *out);
int encode_can_0x0b2_ESP_HR_Radgeschw_02(can_obj_vw_h_t *o, double in);
int decode_can_0x0b2_ESP_VL_Radgeschw_02(const can_obj_vw_h_t *o, double *out);
int encode_can_0x0b2_ESP_VL_Radgeschw_02(can_obj_vw_h_t *o, double in);
int decode_can_0x0b2_ESP_VR_Radgeschw_02(const can_obj_vw_h_t *o, double *out);
int encode_can_0x0b2_ESP_VR_Radgeschw_02(can_obj_vw_h_t *o, double in);


int decode_can_0x120_TSK_Radbremsmom(const can_obj_vw_h_t *o, double *out);
int encode_can_0x120_TSK_Radbremsmom(can_obj_vw_h_t *o, double in);
int decode_can_0x120_TSK_ax_Getriebe_02(const can_obj_vw_h_t *o, double *out);
int encode_can_0x120_TSK_ax_Getriebe_02(can_obj_vw_h_t *o, double in);
int decode_can_0x120_CHECKSUM(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_CHECKSUM(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x120_TSK_zul_Regelabw(const can_obj_vw_h_t *o, double *out);
int encode_can_0x120_TSK_zul_Regelabw(can_obj_vw_h_t *o, double in);
int decode_can_0x120_COUNTER(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_COUNTER(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x120_TSK_Status(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_TSK_Status(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x120_TSK_v_Begrenzung_aktiv(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_TSK_v_Begrenzung_aktiv(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x120_TSK_Standby_Anf_ESP(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_TSK_Standby_Anf_ESP(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x120_TSK_Freig_Verzoeg_Anf(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_TSK_Freig_Verzoeg_Anf(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x120_TSK_Limiter_ausgewaehlt(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_TSK_Limiter_ausgewaehlt(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x120_TSK_Zwangszusch_ESP(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x120_TSK_Zwangszusch_ESP(can_obj_vw_h_t *o, uint8_t in);


int decode_can_0x126_Assist_Torque(const can_obj_vw_h_t *o, uint16_t *out);
int encode_can_0x126_Assist_Torque(can_obj_vw_h_t *o, uint16_t in);
int decode_can_0x126_CHECKSUM(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_CHECKSUM(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_SET_ME_0XFE(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_SET_ME_0XFE(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_SET_ME_0X07(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_SET_ME_0X07(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_SET_ME_0X3(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_SET_ME_0X3(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_COUNTER(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_COUNTER(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_Assist_Requested(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_Assist_Requested(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_Assist_VZ(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_Assist_VZ(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_HCA_Available(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_HCA_Available(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_HCA_Standby(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_HCA_Standby(can_obj_vw_h_t *o, uint8_t in);
int decode_can_0x126_HCA_Active(const can_obj_vw_h_t *o, uint8_t *out);
int encode_can_0x126_HCA_Active(can_obj_vw_h_t *o, uint8_t in);


#ifdef __cplusplus
} 
#endif

#endif
